[package]
name = "livia"
version = "0.2.1"
description = "Leitura Inteligente e Visualização de Informações de Armazenamento"
authors = ["Antonio Silva"]
edition = "2021"

[lib]
name = "livia_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
image = { version = "0.25", default-features = false }
ico = "0.4"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
walkdir = "2"
blake3 = "1"

[target.'cfg(windows)'.dependencies]
usn-journal-rs = "0.4.1"
